# Generated by Django 3.1.4 on 2022-03-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='organizationName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
