# Generated by Django 3.1.4 on 2022-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_users_organizationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
