# Generated by Django 4.0.3 on 2022-04-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ingredient_alter_userinfo_id_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/foodImages/'),
        ),
    ]
