# Generated by Django 4.0.3 on 2022-03-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userinfo_alter_task_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
