# Generated by Django 3.1.4 on 2022-03-30 03:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220329_2307'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
