# Generated by Django 4.0.3 on 2022-03-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('organizationName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
