# Generated by Django 3.1.4 on 2022-03-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220329_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='organizationName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
