# Generated by Django 3.1.4 on 2022-03-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220329_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
